name: "Continuous Integration"

on:
  push:
    branches: [ testBranch ]

jobs:
  phpunit-mariadb:
    name: "PHPUnit with MariaDB"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - "5.4"
        mariadb-version:
          - "10.3"
        extension:
          - "pdo_mysql"

    services:
      mariadb:
        image: "mariadb:${{ matrix.mariadb-version }}"
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: "doctrine"
          MYSQL_USER: "travis"

        options: >-
          --health-cmd "mysqladmin ping --silent"
        ports:
          - "3306:3306"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 2

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: "pcov"
          ini-values: "zend.assertions=1"
          extensions: "${{ matrix.extension }}"

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Set up bootstrap files
        run: |
          cp .travis/mysql_bootstrap_doctrine.php tests/doctrine/bootstrap_doctrine.php
          cp .travis/mysql_bootstrap_pdo.php tests/doctrine/bootstrap_pdo.php
          echo $PWD

      #- name: "Run PHPUnit"
      #  run: "vendor/bin/phpunit --coverage-clover=coverage.xml tests/DoctrineTestSuite1.php"
