name: PHP Composer

on:
  push:
    branches: [ testBranch ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Travis setup
      run: .travis/setup

    - name: List var/run in the repository
      run: |
        ls /var/run

    - name: Create database
      run: mysql -e 'CREATE DATABASE doctrine;'

    - name: Run Travis
      run: .travis/run_tests.sh
